# Generated by Django 3.2.20 on 2023-07-28 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='regTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 30, 53, 930766, tzinfo=utc)),
        ),
    ]
