# Generated by Django 3.2.20 on 2023-07-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AlterField(
            model_name='user',
            name='artist',
            field=models.ManyToManyField(related_name='fans', to='artist.Artist'),
        ),
    ]
