# Generated by Django 3.2.20 on 2023-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('user', '0002_auto_20230728_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='artist',
        ),
        migrations.AddField(
            model_name='user',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
    ]
