# Generated by Django 3.2.20 on 2023-07-28 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('openChatURL', models.URLField(null=True)),
                ('regTime', models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 6, 54, 368966, tzinfo=utc))),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
