# Generated by Django 3.2.20 on 2023-07-28 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='regTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 17, 3, 458327, tzinfo=utc)),
        ),
    ]
