# Generated by Django 3.2.20 on 2023-07-28 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=200)),
                ('regTime', models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 6, 54, 368610, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('가수', 'artist'), ('자유', 'free')], default='가수', max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField(max_length=1000)),
                ('regTime', models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 6, 54, 368272, tzinfo=utc))),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
    ]
