# Generated by Django 3.2.20 on 2023-07-28 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20230728_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='regTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 30, 53, 929539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='regTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 30, 53, 929192, tzinfo=utc)),
        ),
    ]
