# Generated by Django 3.2.20 on 2023-07-28 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20230728_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='regTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 31, 49, 30294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='regTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 7, 31, 49, 29942, tzinfo=utc)),
        ),
    ]
