# Generated by Django 3.2.20 on 2023-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=200, null=True)),
                ('artistImage', models.ImageField(upload_to='')),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('debutDate', models.DateField()),
                ('color', models.CharField(max_length=30)),
                ('fanName', models.CharField(max_length=30)),
                ('agency', models.CharField(max_length=30)),
            ],
        ),
    ]
