# Generated by Django 3.2.20 on 2023-07-28 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userWorking', '0002_alter_userworking_startlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworking',
            name='startLike',
            field=models.DateField(verbose_name=datetime.datetime(2023, 7, 28, 7, 30, 53, 930268, tzinfo=utc)),
        ),
    ]
