# Generated by Django 3.2.20 on 2023-07-27 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userWorking', '0007_alter_userworking_startlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworking',
            name='startLike',
            field=models.DateField(verbose_name=datetime.datetime(2023, 7, 27, 13, 57, 38, 399635, tzinfo=utc)),
        ),
    ]
