# Generated by Django 3.2.20 on 2023-07-27 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userWorking', '0011_alter_userworking_startlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworking',
            name='startLike',
            field=models.DateField(verbose_name=datetime.datetime(2023, 7, 27, 15, 18, 33, 743818, tzinfo=utc)),
        ),
    ]
